# Generated by Django 2.2.3 on 2019-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'contact_types',
            },
        ),
    ]
