# Generated by Django 2.2.3 on 2019-08-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_type',
            new_name='contact_types',
        ),
    ]
