# Generated by Django 2.2.3 on 2019-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('ipadd', models.CharField(default='0.0.0.0/0', max_length=100)),
                ('tagline', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'sites',
            },
        ),
    ]
