# Generated by Django 2.2.3 on 2019-08-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=10)),
                ('contact_number', models.CharField(default='', max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netinfo.sites')),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
