# Generated by Django 2.2.3 on 2019-09-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='contact_number',
            new_name='contact_data',
        ),
    ]
