# Generated by Django 2.2.3 on 2019-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netinfo', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='add_field1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='add_field2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='add_field3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='add_field4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
